name: Auto commit

on:
  push:
    branches:
      - master
  schedule:
    # Menjalankan setiap 6 jam sekali (00:00, 06:00, 12:00, 18:00) 
    # agar tidak terlalu "nyepam" hingga ribuan commit.
    - cron: "0 */6 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true # Diubah ke true agar bisa push langsung
          fetch-depth: 0

      - name: Modify last update
        run: |
          date '+%Y-%m-%dT%H:%M:%SZ' > LAST_UPDATED
          
      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          git config --local user.email "mmuhammadiqbal963@gmail.com"
          git config --local user.name "iqbal2604"
          
          git add LAST_UPDATED
          
          # Array pesan commit
          arr=("chore(bot): 😂 auto commit" "chore(bot): 😱 auto commit" "chore(bot): 👿 auto commit" "chore(bot): 💩 auto commit" "chore(bot): 🙏 auto commit" "chore(bot): 🙈 auto commit" "chore(bot): 🐐 auto commit" "chore(bot): 🤖 auto commit" "chore(bot): 🟩 auto commit" "chore(bot): 👻 auto commit")
          
          # Pilih pesan secara acak
          rand=$(( RANDOM % ${#arr[@]} ))
          
          # Commit hanya jika ada perubahan
          git commit -m "${arr[$rand]}" || exit 0
          
          # Push langsung menggunakan token
          git push origin master
